services:
  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: devportfolio-frontend
    ports:
      - "5000:3000"
    volumes:
      - ../DevPortfolio/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
